<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "messageboard"
 *
 * Auto generated by Extension Builder 2020-04-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'A simple message board for the frontend users',
    'description' => 'The fe users can publish a message for other fe users.',
    'category' => 'plugin',
    'author' => 'Clemens Gogolin',
    'author_email' => 'service@cylancer.net',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => true,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];


/* CHANGLOG: 
      2.0.0 :: Fix the plugin registration/configuration.
 */